# /etc/network/interfaces

#source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# Physical Interface
auto enp0s3
iface enp0s3 inet manual

# VLAN 1
auto enp0s3.1
iface enp0s3.1 inet static
        address 10.10.1.2
        netmask 255.255.255.0
        gateway 10.10.10.1
        dns-nameservers 8.8.8.8 8.8.4.4
        vlan-raw-device enp0s3

############################################################
# VLAN Client Template (replace existing settings)
############################################################
# -- The Physical Interface (Must be UP to carry VLAN traffic)
# auto <PHYSICAL_IF>
# iface <PHYSICAL_IF> inet manual

# -- The Virtual VLAN Interface
# auto <PHYSICAL_IF>.<VLAN_ID>
# iface <PHYSICAL_IF>.<VLAN_ID> inet static
#    address <CLIENT_IP>             # The IP of this specific VM
#    netmask 255.255.255.0           # Standard Class C subnet
#    gateway <ROUTER_VLAN_IP>        # The Router's IP for this specific VLAN
#    dns-nameservers 8.8.8.8 8.8.4.4 # DNS for web browsing
#    vlan-raw-device <PHYSICAL_IF>   # Ties this virtual ID to the hardware
############################################################
