# sudo nano /etc/sysctl.d/99-router.conf
# Brute force if sysctl.conf is overwritten by system default

# Enable IPv4 packet forwarding to allow routing between VLANs and Internet
net.ipv4.ip_forward=1