# /etc/network/interfaces

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# Physical Interface
auto enp0s8
iface enp0s8 inet manual

# VLAN 10 Segmentation
auto enp0s8.10
iface enp0s8.10 inet static
    address 10.10.10.1
    netmask 255.255.255.0
    vlan-raw-device enp0s8

# VLAN 20 Segmentation
auto enp0s8.20
iface enp0s8.20 inet static
    address 10.20.20.1
    netmask 255.255.255.0
    vlan-raw-device enp0s8

############################################################
# Router Template
############################################################
# -- The Physical LAN Interface
# auto <LAN_IF>
# iface <LAN_IF> inet manual

# -- VLAN <id> Gateway
# auto <LAN_IF>.<VLAN_ID>
# iface <LAN_IF>.<VLAN_ID> inet static
#    address <VLAN_ID_GW_IP>         # The IP of this specific VM
#    netmask 255.255.255.0           # Standard Class C subnet
#    vlan-raw-device <LAN_IF>   	 # Ties this virtual ID to the hardware
############################################################